name: Notify Discord on Pull Requests

on:
  pull_request:
    types: [opened, closed]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          ACTION: ${{ github.event.action }}
          MERGED: ${{ github.event.pull_request.merged }}
        run: |
          if [ "$ACTION" = "opened" ]; then
            MESSAGE="📢 Pull Request mới từ **$PR_USER**: [$PR_TITLE]($PR_URL)"
          elif [ "$ACTION" = "closed" ] && [ "$MERGED" = "true" ]; then
            MESSAGE="✅ Pull Request đã được **merged**: [$PR_TITLE]($PR_URL) bởi $PR_USER"
          else
            MESSAGE=""
          fi

          if [ "$MESSAGE" != "" ]; then
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\": \"$MESSAGE\"}" \
                 $DISCORD_WEBHOOK
          fi
